### ISSUE TITLE
Getting started with some web framework

### ISSUE THREAD

**Issue by jwoertink** [mperham/sidekiq.cr#76]
I'm having some issues trying to figure out how to boot this version along with my Lucky app. I've used the Ruby version, so I'm familiar with how that all works.

It looks like I need this as a minimum:
```crystal
require "sidekiq/cli"

cli = Sidekiq::CLI.new
server = cli.configure do |config|
end
```

Without that, calling any worker will throw an exception `Sidekiq client has not been configured yet (Exception)` even if I have the ENV vars setup. 

But with that config, I now want to boot the sidekiq process. If I add the `cli.run(server)` in this file, then boot my app with `crystal src/server.cr`, it hits the sidekiq config and boots the server, then stops the lucky server from booting. I obviously need a process manager for this to work. 

I tried adding a target to my shard.yml

```yml
targets:
  my_app:
    main: src/my_app.cr
  sidekiq:
    main: src/sidekiq.cr
```

Then I run `shards build` and end up getting some `ld: library not found for -lcrt0.o (this usually means you need to install the development package for libcrt0.o)` error.

Finally I decide to just putting `worker: crystal src/sidekiq.cr` in to my Procfile where I can just run `lucky dev` and have it boot. This fails though with the error `You must register one or more workers to execute jobs!`. So I have to require my workers specifically. So I add `require "./workers/*"` to the file, and now I get a compilation error because it doesn't know about any of the Lucky stuff. 

I guess I could require all of that stuff twice, but at this point I feel like I'm not understanding the process and it's more just band-aids.

**Comment by jgaskins** [comment]
Your `shards build` error seems really weird and I wonder if it might be a CrystalShards bug. If `crystal build` works, then it seems `shards build` should, as well. I'd like to think that `shards build` simply runs `crystal build` across all of the `targets`, but that could just be me Dunning-Krugering a very useful tool.

> I guess I could require all of that stuff twice

Since your web app and your Sidekiq app are two different Crystal programs, it kinda makes sense to specify their dependencies separately. It might be worthwhile to extract the common requires into a single file, similarly to how Rails lets you just load `config/environment.rb`.

Personally, I require all my dependencies per-file so I can load any file at any time. That doesn't seem to be a Lucky convention, but I almost never need to think about transitive dependencies. If my Sidekiq worker loads the models it uses, the models load the model superclass, and the model superclass loads the DB config, requiring the worker is all I need to do to enable that worker.

**Comment by jwoertink** [comment]
Yeah, I actually ended up using a different job processor which had a somewhat similar setup. Now that I've done it once, it makes more sense that you'd have your main web file and main worker file each requiring the app how it needs. 

Technically *my* issue is solved, but I'll leave this open for now as some documentation, or maybe that build error could help further the project. Buy any maintainers can feel free to close this out if needed.

**Comment by jwoertink** [comment]
Ok, giving sidekiq another shot here, and I'm still not having luck getting this to run. 

```crystal
# config/sidekiq.cr
require "sidekiq"

Sidekiq::Client.default_context = Sidekiq::Client::Context.new
```

Then, for my worker process in `src/worker.cr`, I have to add this same code again just so I can boot the cli?

```crystal
# src/worker.cr

require "./shards"
require "./workers/*"
require "sidekiq/cli"

cli = Sidekiq::CLI.new

server = cli.configure do |config|
end

cli.run(server)
```

```crystal
# src/workers/update_worker.cr
class UpdateWorker
  include Sidekiq::Worker

  def perform(member_id : String)
    logger.info "hello, UpdateWorker"
  end
end
```

```crystal
# src/actions/login/create.cr

post "/login" do
  #... 
  UpdateWorker.async.perform(member_id: "abc123")
end
```

I boot my app and my sidekiq process, then kick off a job. I see the keys get set in the redis-cli, but there's nothing logged out on the worker process STDOUT, and none of the jobs seem to actually run. 

I'm not sure what I'm missing here...

**Comment by jgaskins** [comment]
[This](https://github.com/jgaskins/sidekiq_lucky_example/commit/cd9a7dfc869cff48bd57f48d8395ec824e4e4cb0) worked on top of a freshly initialized Lucky app.

<details>
  <summary>App logs</summary>

## Web app

```
➜  sidekiq_lucky_example git:(master) ✗ PORT=5050 lucky watch
Beginning to watch your project
Compiling...
Done compiling


   🎉 App running at http://127.0.0.1:5050



POST /foo
 ▸ Handled by Foo::Create
 ▸ Ran verify_accepted_format
 ▸ Sent 200 (9.01ms)
```

## Sidekiq

```
➜  sidekiq_lucky_example git:(master) ✗ crystal src/worker.cr


         m,
         `$b
    .ss,  $$:         .,d$
    `$$P,d$P'    .,md$P"'
     ,$$$$$bmmd$$$P^'
   .d$$$$$$$$$$P'
   $$^' `"^$$$'       ____  _     _      _    _
   $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
   `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
          $$:         ___) | | (_| |  __/   <| | (_| |
          $$         |____/|_|\__,_|\___|_|\_\_|\__, |
        .d$$                                       |_|

2020-01-29T02:26:55.161Z 39301 TID-1zeop4g  INFO: Sidekiq v0.6.1 in Crystal 0.32.1
2020-01-29T02:26:55.161Z 39301 TID-1zeop4g  INFO: Licensed for use under the terms of the GNU LGPL-3.0 license.
2020-01-29T02:26:55.161Z 39301 TID-1zeop4g  INFO: Upgrade to Sidekiq Enterprise for more features and support: http://sidekiq.org
2020-01-29T02:26:55.161Z 39301 TID-1zeop4g  INFO: Starting processing with 25 workers
2020-01-29T02:26:55.161Z 39301 TID-1zeop4g  INFO: Press Ctrl-C to stop
2020-01-29T02:26:55.173Z 39301 TID-1zeoo4g  JID=a64a23f8890e88b1ebbdd93c INFO: Start
2020-01-29T02:26:55.173Z 39301 TID-1zeoo4g  JID=a64a23f8890e88b1ebbdd93c INFO: hello, UpdateWorker
2020-01-29T02:26:55.173Z 39301 TID-1zeoo4g  JID=a64a23f8890e88b1ebbdd93c INFO: Done: 0.000062 sec
```

## Curl

```
➜  sidekiq_lucky_example git:(master) ✗ curl -X POST localhost:5050/foo -d 'foo=bar'
Render something in Foo::Create%
```

**Comment by jwoertink** [comment]
Interesting. That's the same thing I have, but I never see the log output 🤔 My app isn't a fresh lucky app though. I'll keep digging in to see what's going on, but glad to see it does in fact work on a fresh app! Thanks for taking a look at that @jgaskins

**Comment by hugopl** [comment]
Could I close this? The documentation still not good, but at least the problem seems to had been solved :wink:.
